
translate rus strings:
    old "New version available!"
    new "Новая версия доступна!"
    old "Can't check for update!"
    new "Не удалось проверить наличие обновлений!"
    old "{color=#7c76b3}Report a bug{/color}"
    new "{color=#7c76b3}Сообщить об ошибке{/color}"
    old "{color=#7c76b3}Game wiki{/color}"
    new "{color=#7c76b3}Игровая вики{/color}"
    old "Back"
    new "Назад"
    old "History"
    new "История"
    old "Skip"
    new "Пропуск"
    old "Auto"
    new "Авто"
    old "Save"
    new "Сох."
    old "Q.Save"
    new "Б. сох."
    old "Q.Load"
    new "Б. заг."
    old "Prefs"
    new "Настройки"
    old "Start"
    new "Начать игру"
    old "Load"
    new "Загрузить"
    old "Settings"
    new "Настройки"
    old "End Replay"
    new "End Replay"
    old "Main Menu"
    new "Главное Меню"
    old "Quit"
    new "Выход"
    old "Return"
    new "Назад"
    old "About"
    new "Об игре"
    old "Version [config.version!t]\n"
    new "Version [config.version!t]\n"
    old "Made with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    new "Made with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    old "Page {}"
    new "Страница {}"
    old "Automatic saves"
    new "Авто-сохранения"
    old "Quick saves"
    new "Быстрые сохранения"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%A, %B %d %Y, %H:%M"
    old "empty slot"
    new "Пусто"
    old "<"
    new "<"
    old "{#auto_page}A"
    new "{#auto_page}A"
    old "{#quick_page}Q"
    new "{#quick_page}Q"
    old ">"
    new ">"
    old "Preferences"
    new "Настройки"
    old "Display"
    new "Режим"
    old "Window"
    new "В окне"
    old "Fullscreen"
    new "Полноэкранный"
    old "Rollback Side"
    new "Сторона откатов"
    old "Disable"
    new "Отключено"
    old "Left"
    new "Левая"
    old "Right"
    new "Правая"
    old "Unseen Text"
    new "Всего текста"
    old "After Choices"
    new "После выборов"
    old "Transitions"
    new "Переходов"
    old "Language"
    new "Язык"
    old "English"
    new "Английский"
    old "Russian"
    new "Русский"
    old "Text Speed"
    new "Скорость текста"
    old "Auto-Forward Time"
    new "Скорость авточтения"
    old "Music Volume"
    new "Громкость музыки"
    old "Sound Volume"
    new "Громкость звуков"
    old "Test"
    new "Test"
    old "Voice Volume"
    new "Громкость голоса"
    old "Mute All"
    new "Заглушить все"
    old "The dialogue history is empty."
    new "История пуста"
    old "Help"
    new "Помощь"
    old "Keyboard"
    new "Клавиатура"
    old "Mouse"
    new "Мышь"
    old "Gamepad"
    new "Геймпад"
    old "Enter"
    new "Enter"
    old "Advances dialogue and activates the interface."
    new "Advances dialogue and activates the interface."
    old "Space"
    new "Пробел"
    old "Advances dialogue without selecting choices."
    new "Advances dialogue without selecting choices."
    old "Arrow Keys"
    new "Клашиви стрелок"
    old "Navigate the interface."
    new "Навигация по интерфейсу"
    old "Escape"
    new "Escape"
    old "Accesses the game menu."
    new "Меню"
    old "Ctrl"
    new "Ctrl"
    old "Skips dialogue while held down."
    new "Пропуск диалогов при зажатии"
    old "Tab"
    new "Tab"
    old "Toggles dialogue skipping."
    new "Toggles dialogue skipping."
    old "Page Up"
    new "Page Up"
    old "Rolls back to earlier dialogue."
    new "Rolls back to earlier dialogue."
    old "Page Down"
    new "Page Down"
    old "Rolls forward to later dialogue."
    new "Rolls forward to later dialogue."
    old "Hides the user interface."
    new "Hides the user interface."
    old "Takes a screenshot."
    new "Takes a screenshot."
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    old "Opens the accessibility menu."
    new "Opens the accessibility menu."
    old "Left Click"
    new "Left Click"
    old "Middle Click"
    new "Middle Click"
    old "Right Click"
    new "Right Click"
    old "Mouse Wheel Up\nClick Rollback Side"
    new "Mouse Wheel Up\nClick Rollback Side"
    old "Mouse Wheel Down"
    new "Mouse Wheel Down"
    old "Right Trigger\nA/Bottom Button"
    new "Right Trigger\nA/Bottom Button"
    old "Left Trigger\nLeft Shoulder"
    new "Left Trigger\nLeft Shoulder"
    old "Right Shoulder"
    new "Right Shoulder"
    old "D-Pad, Sticks"
    new "D-Pad, Sticks"
    old "Start, Guide"
    new "Start, Guide"
    old "Y/Top Button"
    new "Y/Top Button"
    old "Calibrate"
    new "Calibrate"
    old "Yes"
    new "Да"
    old "No"
    new "Нет"
    old "Skipping"
    new "Skipping"
    old "Menu"
    new "Меню"
    old "{color=#7c76b3}Suggest an idea{/color}"
    new "{color=#7c76b3}Предложить идею{/color}"
translate rus strings:
    old "Content manager"
    new "Управ. контентом"
    old "NSFW"
    new "NSFW (цензура)"
    old "Enabled"
    new "Включено"
    old "Disabled"
    new "Выключено"
    

translate rus strings:

    # game/screens.rpy:487
    old "Discord status"
    new "Статус в дискорде"

    # game/screens.rpy:498
    old "Help us anonymously monitor game health"
    new "Помогать нам следить за стабильностью игры"

